# Generated by Django 3.1.1 on 2020-09-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200904_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='contente',
            new_name='content',
        ),
    ]
